name: consultation_app
description: "Consultation App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.18.0
  shared_preferences: ^2.3.2
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: ibmFont
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
